In [1]:
%pwd

'C:\\Users\\Hp\\Desktop\\Data Engineering Project\\SAT.Asia Assessment\\ipnyb_files_for_cleaning'

In [2]:
import pandas as pd
import numpy as np

In [3]:
#Read file "devices.csv" to analyse data contain inside csv file for cleaning.
devices_df = pd.read_csv('../devices.csv', index_col = "id")
devices_df.head(5)

,uuid,local_short_id,customer_id,product_id,creator_id,device_group_id,name,unique_id,satuid,type,...,information,setting,description,is_active,last_active_at,created_at,updated_at,deleted_at,extra_attributes,tenant_id
id,,,,,,,,,,,,,,,,,,,,,
154,ed337d3f-1035-4e1e-85bb-5349ac42370e,NaN,NaN,NaN,NaN,47,20283,20283,NaN,sda tag,...,NaN,[],NaN,0,NaN,2020-12-15 18:23:36,2021-04-29 12:02:57,NaN,"{""box"": ""4"", ""mac"": ""1B0ECC502F49"", ""layer"": ""...",56
315,b6a1fbdf-43ee-4dac-93ce-8f32380b70b4,NaN,NaN,NaN,NaN,47,48067,48067,NaN,sda tag,...,NaN,[],NaN,0,NaN,2020-12-15 18:23:37,2021-04-29 12:02:57,NaN,"{""box"": ""12"", ""mac"": ""A8B96D57C2B7"", ""layer"": ...",56
324,e673883c-0a4c-4bcb-9c1e-9a65660d4a01,NaN,NaN,NaN,NaN,47,13674,13674,NaN,sda tag,...,NaN,[],NaN,0,NaN,2020-12-24 04:18:56,2021-04-29 12:02:57,NaN,"{""mac"": ""AFCC793F9ABB""}",56
325,ea8f61ca-6c9b-42f0-9f79-050b125e753f,NaN,NaN,NaN,NaN,47,13367,13367,NaN,sda tag,...,NaN,[],NaN,0,NaN,2020-12-24 04:18:56,2021-04-29 12:02:57,NaN,"{""mac"": ""635F9F760DE1""}",56
326,5fb88e44-b60c-4da7-8376-325ff0f79411,NaN,NaN,NaN,NaN,47,52566,52566,NaN,sda tag,...,NaN,[],NaN,0,NaN,2020-12-24 04:18:56,2021-04-29 12:02:57,NaN,"{""mac"": ""AAF6DBA8725D""}",56

In [4]:
#Acquire information about the file.

print(devices_df.columns)

print("----------------")

print(devices_df.shape)

print("----------------")

devices_df.info()

print("----------------")

Index(['uuid', 'local_short_id', 'customer_id', 'product_id', 'creator_id',
       'device_group_id', 'name', 'unique_id', 'satuid', 'type', 'status',
       'battery_level', 'sensors', 'value_mappings', 'location', 'version',
       'serial_number', 'information', 'setting', 'description', 'is_active',
       'last_active_at', 'created_at', 'updated_at', 'deleted_at',
       'extra_attributes', 'tenant_id'],
      dtype='object')
----------------
(1046, 27)
----------------
<class 'pandas.core.frame.DataFrame'>
Int64Index: 1046 entries, 154 to 1389
Data columns (total 27 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   uuid              1046 non-null   object
 1   local_short_id    0 non-null      float64
 2   customer_id       0 non-null      float64
 3   product_id        0 non-null      float64
 4   creator_id        0 non-null      float64
 5   device_group_id   1046 non-null   int64
 6   name              1046 non-null   int64
 7   unique_id         1046 non-null   int64
 8   satuid            0 non-null      float64
 9   type              1046 non-null   object
 10  status            0 non-null      float64
 11  battery_level     0 non-null      float64
 12  sensors           0 non-null      float64
 13  value_mappings    0 non-null      float64
 14  location          0 non-null      float64
 15  version           0 non-null      float64
 16  serial_number     0 non-null      float64
 17  information       0 non-null      float64
 18  setting           1046 non-null   object
 19  description       0 non-null      float64
 20  is_active         1046 non-null   int64
 21  last_active_at    120 non-null    object
 22  created_at        1046 non-null   object
 23  updated_at        1046 non-null   object
 24  deleted_at        0 non-null      float64
 25  extra_attributes  1046 non-null   object
 26  tenant_id         1046 non-null   int64
dtypes: float64(15), int64(5), object(7)
memory usage: 228.8+ KB
----------------

In [5]:
#Identify sum of null values in csv file.
nullvalue_sum = devices_df.isnull().sum()
nullvalue_sum[0:]

uuid                   0
local_short_id      1046
customer_id         1046
product_id          1046
creator_id          1046
device_group_id        0
name                   0
unique_id              0
satuid              1046
type                   0
status              1046
battery_level       1046
sensors             1046
value_mappings      1046
location            1046
version             1046
serial_number       1046
information         1046
setting                0
description         1046
is_active              0
last_active_at       926
created_at             0
updated_at             0
deleted_at          1046
extra_attributes       0
tenant_id              0
dtype: int64

In [6]:
temp = devices_df.dropna(axis = 1, how = 'any')
temp.head(10)

,uuid,device_group_id,name,unique_id,type,setting,is_active,created_at,updated_at,extra_attributes,tenant_id
id,,,,,,,,,,,
154,ed337d3f-1035-4e1e-85bb-5349ac42370e,47,20283,20283,sda tag,[],0,2020-12-15 18:23:36,2021-04-29 12:02:57,"{""box"": ""4"", ""mac"": ""1B0ECC502F49"", ""layer"": ""...",56
315,b6a1fbdf-43ee-4dac-93ce-8f32380b70b4,47,48067,48067,sda tag,[],0,2020-12-15 18:23:37,2021-04-29 12:02:57,"{""box"": ""12"", ""mac"": ""A8B96D57C2B7"", ""layer"": ...",56
324,e673883c-0a4c-4bcb-9c1e-9a65660d4a01,47,13674,13674,sda tag,[],0,2020-12-24 04:18:56,2021-04-29 12:02:57,"{""mac"": ""AFCC793F9ABB""}",56
325,ea8f61ca-6c9b-42f0-9f79-050b125e753f,47,13367,13367,sda tag,[],0,2020-12-24 04:18:56,2021-04-29 12:02:57,"{""mac"": ""635F9F760DE1""}",56
326,5fb88e44-b60c-4da7-8376-325ff0f79411,47,52566,52566,sda tag,[],0,2020-12-24 04:18:56,2021-04-29 12:02:57,"{""mac"": ""AAF6DBA8725D""}",56
349,68eba7b0-ac55-412d-9657-a4f53147cab8,47,30054,30054,sda tag,[],0,2021-03-25 17:18:29,2021-04-29 12:02:57,"{""box"": ""1"", ""mac"": ""E6498F104A2B"", ""layer"": ""...",56
350,3b1b78e2-34fb-4ea5-9614-762d5a58cfd6,47,47964,47964,sda tag,[],1,2021-03-25 17:18:29,2021-04-29 12:02:57,"{""box"": ""1"", ""mac"": ""F100027477E8"", ""layer"": ""...",56
351,26a1c052-333a-40fb-86c0-fd027d0012c3,47,14448,14448,sda tag,[],0,2021-03-25 17:18:29,2021-04-29 12:02:57,"{""box"": ""1"", ""mac"": ""9A472DC3D813"", ""layer"": ""...",56
352,0b941498-52d2-40ac-8834-06afb4d57c5f,47,10606,10606,sda tag,[],0,2021-03-25 17:18:29,2021-04-29 12:02:57,"{""box"": ""1"", ""mac"": ""657C88AB958B"", ""layer"": ""...",56
353,fdb0ddd5-e7fc-4050-b56c-427a4589644b,47,2875,2875,sda tag,[],0,2021-03-25 17:18:29,2021-04-29 12:02:57,"{""box"": ""1"", ""mac"": ""7A8C7BBBDC01"", ""layer"": ""...",56

In [7]:
temp.shape

(1046, 11)

In [8]:
temp.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1046 entries, 154 to 1389
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   uuid              1046 non-null   object
 1   device_group_id   1046 non-null   int64
 2   name              1046 non-null   int64
 3   unique_id         1046 non-null   int64
 4   type              1046 non-null   object
 5   setting           1046 non-null   object
 6   is_active         1046 non-null   int64
 7   created_at        1046 non-null   object
 8   updated_at        1046 non-null   object
 9   extra_attributes  1046 non-null   object
 10  tenant_id         1046 non-null   int64
dtypes: int64(5), object(6)
memory usage: 98.1+ KB

In [9]:
devices_df2 = temp
devices_df2.head(10)

,uuid,device_group_id,name,unique_id,type,setting,is_active,created_at,updated_at,extra_attributes,tenant_id
id,,,,,,,,,,,
154,ed337d3f-1035-4e1e-85bb-5349ac42370e,47,20283,20283,sda tag,[],0,2020-12-15 18:23:36,2021-04-29 12:02:57,"{""box"": ""4"", ""mac"": ""1B0ECC502F49"", ""layer"": ""...",56
315,b6a1fbdf-43ee-4dac-93ce-8f32380b70b4,47,48067,48067,sda tag,[],0,2020-12-15 18:23:37,2021-04-29 12:02:57,"{""box"": ""12"", ""mac"": ""A8B96D57C2B7"", ""layer"": ...",56
324,e673883c-0a4c-4bcb-9c1e-9a65660d4a01,47,13674,13674,sda tag,[],0,2020-12-24 04:18:56,2021-04-29 12:02:57,"{""mac"": ""AFCC793F9ABB""}",56
325,ea8f61ca-6c9b-42f0-9f79-050b125e753f,47,13367,13367,sda tag,[],0,2020-12-24 04:18:56,2021-04-29 12:02:57,"{""mac"": ""635F9F760DE1""}",56
326,5fb88e44-b60c-4da7-8376-325ff0f79411,47,52566,52566,sda tag,[],0,2020-12-24 04:18:56,2021-04-29 12:02:57,"{""mac"": ""AAF6DBA8725D""}",56
349,68eba7b0-ac55-412d-9657-a4f53147cab8,47,30054,30054,sda tag,[],0,2021-03-25 17:18:29,2021-04-29 12:02:57,"{""box"": ""1"", ""mac"": ""E6498F104A2B"", ""layer"": ""...",56
350,3b1b78e2-34fb-4ea5-9614-762d5a58cfd6,47,47964,47964,sda tag,[],1,2021-03-25 17:18:29,2021-04-29 12:02:57,"{""box"": ""1"", ""mac"": ""F100027477E8"", ""layer"": ""...",56
351,26a1c052-333a-40fb-86c0-fd027d0012c3,47,14448,14448,sda tag,[],0,2021-03-25 17:18:29,2021-04-29 12:02:57,"{""box"": ""1"", ""mac"": ""9A472DC3D813"", ""layer"": ""...",56
352,0b941498-52d2-40ac-8834-06afb4d57c5f,47,10606,10606,sda tag,[],0,2021-03-25 17:18:29,2021-04-29 12:02:57,"{""box"": ""1"", ""mac"": ""657C88AB958B"", ""layer"": ""...",56
353,fdb0ddd5-e7fc-4050-b56c-427a4589644b,47,2875,2875,sda tag,[],0,2021-03-25 17:18:29,2021-04-29 12:02:57,"{""box"": ""1"", ""mac"": ""7A8C7BBBDC01"", ""layer"": ""...",56

In [12]:
devices_df2.to_csv('../Cleaned_csv_file/devices_clean.csv')

In [13]:
devices_df2.loc[154, 'extra_attributes']

'{"box": "4", "mac": "1B0ECC502F49", "layer": "2", "uniqueid": "20283"}'